### PR TITLE
Respeaker commands use linear volume scale

### PR DESCRIPTION
**Pull request by Anonym-tsk**

### CODE REVIEW

**Review by eouia — COMMENTED** [review]
Thanks for your contribution.
I don't have this device, so cannot test by myself. Previous code was from another volunteer but he might not be an expert.

**Comment by Anonym-tsk** [comment]
I have respeaker clone - waveshare 2-mic array.
Previous code works but uses logarithmic scale. With `-M` flag amixer uses linear scale.

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by Anonym-tsk** [comment]
Yes

**Comment by eouia** [comment]
Ok. tell me your Forum ID(if exists) and remove your current your fork of this module on your account to take over this. then tell me. I'll transfer

**Comment by Anonym-tsk** [comment]
I don't have forum id. Fork is removed.

**Comment by eouia** [comment]
done. Allow transfer, now it's yours.

**Pull request merged**
