### PR TITLE
Different environments note

### PR DESCRIPTION
**Pull request by sergge1**
added note about different environments -> different config should be.
Also attached sample for common config RPi3+Buster+SoundCard

### CODE REVIEW

**Review by eouia — COMMENTED** [review]
I'm worrying your case might be not the common thing. Because ALSA configuration could be somewhat different per device and user.
So I couldn't confirm `Speaker` would be the default than `Master`. More tests would be needed before accepting this PR.
Anyway, thanks for your contribution.

**Comment by sergge1** [comment]
Got it. I had solved my issue with  env so thought such clarification could be helpful for someone other (i did not changed anything in readmy, I have added a para about different possibilities)

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by eouia** [comment]
Sorry for bothering. This module found new owner now. In the meantime, thanks for everything. I’m quitting.

**Pull request closed without merging**
